vim.keymap.set("i", "<C-l>", function()
  require("copilot.suggestion").accept()
end)
vim.keymap.set("i", "<C-j>", function()
  require("copilot.suggestion").next()
end)
vim.keymap.set("i", "<C-k>", function()
  require("copilot.suggestion").prev()
end)
vim.keymap.set("i", "<C-h>", function()
  require("copilot.suggestion").dismiss()
end)
